import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import { fetchReview, fetchReviews } from "../api/client";
import { PageHeader } from "../components/PageHeader";
import { ReviewFindings } from "../components/ReviewFindings";
import { ReviewSharePanel } from "../components/ReviewSharePanel";
import { ScoreBadge } from "../components/ScoreBadge";
import { ScoreTrendChart } from "../components/ScoreTrendChart";
import { StatusPanel } from "../components/StatusPanel";
import { usePageTitle } from "../hooks/usePageTitle";
import type { Review } from "../types/api";
import { formatDate, requestErrorMessage } from "../utils";

export function ReviewDetail() {
  const { reviewId } = useParams();
  const [review, setReview] = useState<Review | null>(null);
  const [trend, setTrend] = useState<Review[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  usePageTitle(review ? `PR #${review.prNumber}` : "Review Detail");

  useEffect(() => {
    if (!reviewId) {
      setError("The review identifier is missing.");
      setLoading(false);
      return;
    }

    const loadReview = async () => {
      try {
        const selectedReview = await fetchReview(reviewId);
        setReview(selectedReview);

        try {
          setTrend(await fetchReviews(selectedReview.repoId));
        } catch {
          setTrend([selectedReview]);
        }
      } catch (requestError) {
        setError(requestErrorMessage(requestError));
      } finally {
        setLoading(false);
      }
    };

    void loadReview();
  }, [reviewId]);

  if (loading) {
    return <StatusPanel label="LOADING" message="Retrieving Prism review findings..." />;
  }

  if (error || !review) {
    return (
      <StatusPanel
        label="REQUEST ERROR"
        message={error ?? "The selected review could not be found."}
        tone="error"
      />
    );
  }

  return (
    <>
      <PageHeader
        action={<ScoreBadge large score={review.score} />}
        description={`${review.repoFullName} / PR #${review.prNumber} / ${formatDate(review.createdAt)}`}
        eyebrow="REVIEW DETAIL"
        title={review.prTitle}
      />

      <ReviewSharePanel
        initialShareUrl={review.shareUrl ?? null}
        initiallyShareable={review.isShareable ?? false}
        key={reviewId}
        reviewId={reviewId ?? ""}
      />

      {review.prSummary?.trim() && (
        <section className="panel relative mb-xl overflow-hidden border-l-4 border-l-primary bg-surface-container-high/40 p-lg shadow-lg shadow-primary/5">
          <div className="absolute left-0 right-0 top-0 h-[1px] bg-gradient-to-r from-primary/30 to-transparent" />
          <header className="mb-sm flex flex-wrap items-center justify-between gap-sm">
            <p className="label-caps font-semibold text-primary">PR Summary</p>
            <p className="font-mono text-code-sm text-outline">Generated by Prism</p>
          </header>
          <p className="max-w-4xl text-body-md leading-relaxed text-on-surface">
            {review.prSummary}
          </p>
        </section>
      )}

      <ReviewFindings comments={review.comments} />

      <ScoreTrendChart reviews={trend.length > 0 ? trend : [review]} />
    </>
  );
}
