import axios from "axios";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { fetchSharedReview } from "../api/client";
import { Logo } from "../components/Logo";
import { ReviewFindings } from "../components/ReviewFindings";
import { ScoreBadge } from "../components/ScoreBadge";
import { StatusPanel } from "../components/StatusPanel";
import { usePageTitle } from "../hooks/usePageTitle";
import type { SharedReview as SharedReviewResponse } from "../types/api";
import { formatDate } from "../utils";

type SharedReviewError = "disabled" | "missing" | "request" | null;

export function SharedReview() {
  const { shareToken } = useParams();
  const [review, setReview] = useState<SharedReviewResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<SharedReviewError>(null);

  usePageTitle(review ? review.prTitle : "Shared Review");

  useEffect(() => {
    const loadSharedReview = async () => {
      if (!shareToken) {
        setError("missing");
        setLoading(false);
        return;
      }

      try {
        setReview(await fetchSharedReview(shareToken));
      } catch (requestError) {
        if (axios.isAxiosError(requestError) && requestError.response?.status === 403) {
          setError("disabled");
        } else if (axios.isAxiosError(requestError) && requestError.response?.status === 404) {
          setError("missing");
        } else {
          setError("request");
        }
      } finally {
        setLoading(false);
      }
    };

    void loadSharedReview();
  }, [shareToken]);

  const content = (() => {
    if (loading) {
      return <StatusPanel label="LOADING" message="Retrieving shared Prism review..." />;
    }

    if (error === "disabled") {
      return (
        <StatusPanel
          label="SHARING DISABLED"
          message="This review is no longer public."
          tone="error"
        />
      );
    }

    if (error === "missing") {
      return (
        <StatusPanel
          label="LINK NOT FOUND"
          message="This shared review link could not be found."
          tone="error"
        />
      );
    }

    if (error === "request" || !review) {
      return (
        <StatusPanel
          label="REQUEST ERROR"
          message="The public review could not be loaded."
          tone="error"
        />
      );
    }

    return (
      <>
        <header className="mb-xl flex flex-wrap items-end justify-between gap-lg border-b border-structure pb-lg">
          <div className="min-w-0 flex-1">
            <p className="label-caps mb-sm">PUBLIC REVIEW</p>
            <h1 className="break-words text-headline-md text-on-surface">{review.prTitle}</h1>
            <p className="mt-sm max-w-2xl font-mono text-code-md text-secondary">
              {review.repoFullName}
            </p>
          </div>
          <ScoreBadge large score={review.score} />
        </header>

        {review.prSummary.trim() && (
          <section className="panel relative mb-xl overflow-hidden border-l-4 border-l-primary bg-surface-container-high/40 p-lg shadow-lg shadow-primary/5">
            <div className="absolute left-0 right-0 top-0 h-[1px] bg-gradient-to-r from-primary/30 to-transparent" />
            <header className="mb-sm flex flex-wrap items-center justify-between gap-sm">
              <p className="label-caps font-semibold text-primary">PR Summary</p>
              <p className="font-mono text-code-sm text-outline">Generated by Prism</p>
            </header>
            <p className="max-w-4xl text-body-md leading-relaxed text-on-surface">
              {review.prSummary}
            </p>
          </section>
        )}

        <ReviewFindings comments={review.comments} />

        <footer className="mt-xl border-t border-structure pt-lg font-mono text-code-sm text-outline">
          Reviewed by Prism {"\u00b7"} {formatDate(review.createdAt)}
        </footer>
      </>
    );
  })();

  return (
    <main className="min-h-screen px-md py-lg sm:px-lg lg:py-xl">
      <div className="mx-auto max-w-content">
        <div className="mb-xl flex items-center justify-between border-b border-structure pb-lg">
          <Link aria-label="Prism home" to="/">
            <Logo />
          </Link>
          <Link className="button-ghost" to="/">
            View on Prism
          </Link>
        </div>
        {content}
      </div>
    </main>
  );
}
